Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,13 +33,32 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
-      - name: Release
-        env:
-          BINTRAY_USER: jenkins-reform-hmcts
-          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
-          RELEASE_VERSION: ${{ github.ref }}
-        run: ./gradlew bintrayUpload --info
-        if: startsWith(github.ref, 'refs/tags')
+      - name: Release Build in JitPack
+        run: |
+          echo "Triggering JitPack build"
+
+          PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
+          PACKAGES_FILE="packages.txt"
+          touch ${PACKAGES_FILE}
+          # Try the URL 3 times before failing
+          count=1
+          until [[ $count -gt 3 ]] || [[ $(cat ${PACKAGES_FILE} | wc -l | xargs ) -gt 1 ]] ; do
+            echo "Attempt ${count}/3"
+            STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
+
+            let count+=1
+            sleep 30
+          done
+
+          echo "::group::Files Available"
+          echo $(cat ${PACKAGES_FILE})
+          echo "::endgroup::"
+
+          if [[ ${STATUS} -gt 399 ]] ; then
+            echo "FAILURE: ${STATUS} response from JitPack"
+            exit 1
+          fi
+      if: startsWith(github.ref, 'refs/tags')
       - name: Cleanup Gradle Cache
         run: |
           rm -f ~/.gradle/caches/modules-2/modules-2.lock
